baseURL = 'https://candeiasalexandre.github.io/'
languageCode = 'en-us'
title = ''
theme = "color-your-world"
googleAnalytics = "G-STBQ2DT4EZ"
enableRobotsTXT = true

paginate = 100

[markup.goldmark.renderer]
unsafe = true

[params]

# Site description
description = "Alexandre Candeias's personal website"

# Author
author = "Alexandre Candeias"

[params.style]
# Dark mode as default
# User preferences (site/system settings) will still have priority over it
# The default is false
isDark = true
# Accent colors for dark and light mode respectively
darkAccent = "#1dbc91"  # Default is "#1dbc91"
lightAccent = "#1dbc91" # Default is "#1f676b" 
# More colors, pick as many as you want (not really sure if there's a limit)
# Apparently these may not show up on every modern browser (ie.: Firefox)
# There's no default value. Used here just as example
presets = []

[params.social.centralized]
github = ["candeiasalexandre"]
gitlab = ["candeiasalexandre"]
linkedin = ["candeiasalexandre"]
twitter = ["@alexmricandeias"]
#entry         = [ "username", "label (optional)" ]

# The "entry" here IS important. It's used to load the data.

[params.social.decentralized]
# The "entry" here ISN'T important. It's used for nothing.

[menu]
[[menu.main]]
name = "Home"
weight = 1
url = "/"
[[menu.main]]
name = "Posts"
weight = 2
url = "posts/"
[[menu.main]]
name = "CV"
weight = 3
url = "https://docs.google.com/document/d/e/2PACX-1vTaRT4AyD2Z9DhQhDk8uxrMKfhbA0d6mMx4CedIXbMyPlQgAMJtFBqLfGugDFkr8pNXKS3FJTiS1yLX/pub"
